<?php
/*
  $Id: footer.php, v 2.2 24/07/2003 by Paulo Cezar - Artsampa Exp $

  osCommerce
  http://www.oscommerce.com/

  Artsampa - Graffiti Art Shop
  http://www.artsampa.com/

  Copyright (c) 2000,2003 osCommerce

  Released under the GNU General Public License
 
*/

  require(DIR_WS_INCLUDES . 'counter.php');
?>
<table border="0" width="100%" cellspacing="0" cellpadding="1">
  <tr class="footer">
    <td class="footer" align="center"><FONT FACE="Verdana, Arial" size=1 color="#FFFFFF"><?php echo $counter_now?> &nbsp;Visitantes </font>&nbsp; <script language="JavaScript" src="datestamp.js"></script></td>
  </tr>
</table>

<br>
<table border="0" width="100%" cellspacing="0" cellpadding="0">
  <tr>
    <td align="center" class="smallText">

Copyright © 2003 / 2004 - <a href="http://www.artsampa.com" target="_blank">Artsampa.com</a><br> Software Derivado de <a href="http://www.oscommerce.com" target="_blank">osCommerce</a>

<P></td></tr></table><br>
