      <span class="Login"><center><form name="login" method="post" action="login.php?action=process&email_address=">
      <table border="0" width="100%" cellspacing="0" cellpadding="2"><tr>
      <td class="main"><img src="images/seta.gif" width="8" height="13" border="0"> E - Mail:<br> <input type="text" name="email_address" maxlength="30" size=15 value="" style="color: #000000; font-family: Verdana; font-size: 8 pt; background-color: #FFFFFF; border: 1 solid #000000></td></tr><tr>
      <td class="main"><br><img src="images/seta.gif" width="8" height="13" border="0"> Password:<br> <input type="password" name="password" maxlength="30" size=15 value="" style="color: #000000; font-family: Verdana; font-size: 8 pt; background-color: #FFFFFF; border: 1 solid #000000></td></tr><tr>
      <td class="main"><br><input type="radio" name="user" value="new" checked><font size="1"> Novo Usuário</font></td></tr><tr>
      <td class="main"><center><a href="create_account.php"><img src="images/button_go.gif" border="0" alt="Criar Conta"></a></center></td></tr><tr>
      <td class="main"><input type="radio" name="user" value="returning"><font size="1"> Sou Usuário</font></td></tr><tr>
      <td align="center" class="smallText"><input type="image" src="images/button_login.gif" border="0" alt="Login"></td>
      </tr></tr></table></form></center></span>







