<?php
/*
  $Id: shipping.php,v 1.5 2003/07/08 16:45:36 dgw_ Exp $

  osCommerce, Open Source E-Commerce Solutions
  http://www.oscommerce.com

  Copyright (c) 2002 osCommerce

  Released under the GNU General Public License
*/

define('NAVBAR_TITLE', 'Envio e Devolu&ccedil;&otilde;es');
define('HEADING_TITLE', 'Envio e Devolu&ccedil;&otilde;es');

define('TEXT_INFORMATION', '<p align="justify">

1 - <Font color="#000FFF"> Como fa&ccedil;o para comprar na Loja Virtual</Font><br>
R - Basta escolher o produto e clicar no icone Comprar<br>
2 - <Font color="#000FFF"> Eu tenho que pagar a taxa do Correio</Font><br> 
R - Sim, é <b>normal via correio</b> demora entre 5 e 15 dias no Brasil e 15 &aacute; 40 dias para outros pa&iacute;ses, o preço é único para o Brasil todo, e para outros paises &eacute; variado.<br>
3 - <Font color="#000FFF"> Como efetuar o pagamento da compra</Font><br> 
R - Você pode escolher varios tipos de pagamento, estas informações vai junto com seu pedido de compra.<br>
4 - <Font color="#000FFF"> Todo item exposto na loja virtual tem &agrave; pronta entrega</Font><br> 
R - Sim todos<br>
5 - <Font color="#000FFF"> Como vou receber a mercadoria comprada na loja virtual</Font><br> 
R - Voc&ecirc; receber&aacute; pelo correio uma caixa com seu pedido no endere&ccedil;o citado no seu cadastro, ap&oacute;s ter recebido o valor a ser pago pela compra<br>
6 - <Font color="#000FFF"> Como vou receber o aviso de minha compra</Font><br> 
R - Voc&ecirc; receber&aacute; pelo seu e-mail de cadastro na hora em que for efetuar o seu pedido com os dados comprovando sua compra.<br>
7 - <Font color="#000FFF"> Como confirmo que paguei o valor pela compra na loja virtal</Font><br> 
R - Voc&ecirc; envia um e-mail junto com o seu pedido de compra, dizendo quando foi pago o valor comprovando o seu pagamento.<br><br>

<Font color="#000FFF">ATEN&Ccedil;&Atilde;O</font> Ap&oacute;s reservado seu pedido e n&atilde;o pago no prazo de quinze (15) dias, este ser&aacute; automaticamente cancelado.<br><br>

Para maiores informa&ccedil;&otilde;es contate o: &nbsp; &nbsp; &nbsp; <Font color="#FFF000"><A HREF="contact_us.php"><b>Administrador</b></a></Font></p>');
?>
