<?php

define('NAVBAR_TITLE', 'How to Buy');
define('TOP_BAR_TITLE', 'How to Buy');
define('HEADING_TITLE', 'How to Buy');

define('TEXT_INFORMATION', '<p align="justify">
1 - <Font color="#000FFF"> Como faço para comprar no Negócios Compra e Venda</font><br>
R - Basta escolher o produto e clicar no icone Comprar<br>
2 - <Font color="#000FFF"> Eu tenho que pagar a taxa do Correio</font><br> 
R - Sim, temos a <B>Entrega normal / Registrada </b> demora entre 5 e 15 dias, e o preço é único para o Brasil todo, ou <B>Sedex </b> que demora 3 à 5 dias, e o preço é variado de acordo com seu estado no Brasil.<br>
3 - <Font color="#000FFF"> Como efetuar o pagamento da compra</font><br> 
R - Você pode fazer um depósito / transferência no banco Bradesco, estas informações irai junto com seu pedido de compra.<br>
4 - <Font color="#000FFF"> Tem outro jeito de efetuar o pagamento da compra</font><br> 
R - Não.<br>
5 - <Font color="#000FFF"> Todo item exposto no Negócios Compra e Venda tem à pronta entrega</font><br> 
R - Sim todos<br>
6 - <Font color="#000FFF"> Como vou receber a mercadoria comprada no Artshop</font><br> 
R - Você receberá pelo correio uma caixa com seu pedido no endereço citado no formulário entre 3 e 15 dias úteis, apòs 
o Negócios Compra e Venda ter recebido o valor a ser pago pela compra<br>
7 - <Font color="#000FFF"> Como vou receber o aviso de minha compra</font><br> 
R - Você receberá pelo seu e-mail de cadastro na hora em que for efetuar o seu pedido com os dados comprovando sua compra, ou você pode imprimir a folha de seu pedido e guarda-la.<br>
8 - <Font color="#000FFF"> Como confirmo que depositei o valor pago pela compra no Negócios Compra e Venda</font><br> 
R - Você envia um e-mail junto com o seu pedido de compra, dizendo quando foi depositado o valor comprovando o seu pagamento.<br><br>

<Font color="#000FFF">ATENÇÃO</font> Após reservado seu pedido e não pago no prazo de dez (10) dias, este será automaticamente cancelado.<br><br>

Com isso devo ter respondido a maioria das questões de como proceder para uma compra segura e sem erros no Negócios Compra e Venda.       <Font color="#000FFF">Negócios Compra e Venda</font></p>');
?>
