<?php
/*
  $Id: index.php,v 1.1 2002/01/02 13:02:39 hpdl Exp $

  osCommerce, Open Source E-Commerce Solutions
  http://www.oscommerce.com

  Copyright (c) 2002 osCommerce

  Released under the GNU General Public License
*/
?>
<p><span class="pageHeading">Artshop</span><br><font color="#9a9a9a">Loja Virtual osCommerce 2.2 Br</font></p>

<p class="pageTitle">Seja Bem Vindo ao software de instalação de sua loja virtual!</p>

<p>ATENÇÃO: Antes de instalar sua loja virtual é necessário que você crie um banco de dados e um usuário de banco de dados em sua conta. Você conseguirá fazer isso facilmente através do seu painel de controle no link Banco de Dados SQL. Não se esqueça de dar permissão ao usuário sobre o banco de dados.</p>

<p>Após fazer isso basta inserir nos campos que estão em branco os dados de seu banco de dados e seguir os passos de configuração para dentro de alguns segundos você estar com a sua loja virtual no ar. Após a instalação complete as instruções que irão aparecer no topo da página de sua loja.</p>

<p>Este é um software gratuito e de código fonte aberto. A licensa deste software está presente em sua conta no diretório que será criado. Os direitos autorais e a licença de uso devem ser respeitados em sua total integridade.</p>

<p>Caso tenha problemas durante a instalação, entre em contato com o nosso suporte. Para prosseguir clique no botão abaixo.</p>

<table border="0" width="100%" cellspacing="0" cellpadding="0">
  <tr>
    <td align="center"><a href="install.php"><img src="images/button_new_install.gif" border="0" alt="Nova Instalação"></a></td>
    
  </tr>
</table>
