<?php
/*
  $Id: bradesco.php, v 2.2 24/07/2003 by Paulo Cezar - Artsampa Exp $

  osCommerce
  http://www.oscommerce.com/

  Artsampa - Graffiti Art Shop
  http://www.artsampa.com/

  Copyright (c) 2000,2003 osCommerce

  Released under the GNU General Public License
 
*/

  define('MODULE_PAYMENT_BRADESCO_TEXT_TITLE', 'Depósito/Transferência - Bco Bradesco - Brazil');
  define('MODULE_PAYMENT_BRADESCO_TEXT_DESCRIPTION', '');
 
?>