<?php
/*
  $Id: mail.php, v 2.2 24/07/2003 by Paulo Cezar - Artsampa Exp $

  osCommerce
  http://www.oscommerce.com/

  Artsampa - Graffiti Art Shop
  http://www.artsampa.com/

  Copyright (c) 2000,2003 osCommerce

  Released under the GNU General Public License
 
*/

  define('MODULE_PAYMENT_MAIL_TEXT_TITLE', 'Mail Order / Pagamento via Correio');
  define('MODULE_PAYMENT_MAIL_TEXT_DESCRIPTION', 'Mail Order / Pagamento via Correio');
 
?>