<?php
/*
  $Id: footer.php,v 1.1 2002/01/02 13:02:39 hpdl Exp $

  osCommerce, Open Source E-Commerce Solutions
  http://www.oscommerce.com

  Copyright (c) 2002 osCommerce

  Released under the GNU General Public License
*/
?>
<!-- footer //-->
<table border="0" width="780" cellspacing="0" cellpadding="0" align="center">
  <tr>
    <td background="images/header_titlebar_background.gif"><table border="0" width="100%" cellspacing="0" cellpadding="0">
      <tr>
        <td height="20" class="footerBar"><b>&nbsp;<?php echo date("l, jS F, Y"); ?>&nbsp;</b></td>
        <td align="right" height="20" class="footerBar"><b>&nbsp;Bugs? <a href="mailto:nuke@supernuke.com.br"><font color="#ffffff"><u>Comunique-nos!</u></font></a>&nbsp;</b></td>
      </tr>
    </table></td>
  </tr>
  <tr>
    <td align="center" class="smallText"><br>Copyright © 2003 <a target="_blank" href="http://www.artsampa.com"> Artsampa.com</a> &nbsp; Powered by:  <a target="_blank" href="http://www.oscommerce.com">OsCommerce 2.2</a><p></td>
  </tr>
</table>
<!-- footer_eof //-->