<?php
/*
  $Id: footer.php, v 2.2 24/07/2003 by Paulo Cezar - Artsampa Exp $

  osCommerce
  http://www.oscommerce.com/

  Artsampa - Graffiti Art Shop
  http://www.artsampa.com/

  Copyright (c) 2000,2003 osCommerce

  Released under the GNU General Public License
 
*/

?>
<table border="0" width="100%" cellspacing="0" cellpadding="2">
  <tr class="footer">
    <td align="center" class="smallText"><?php echo strftime(DATE_FORMAT_LONG); ?></td>
  </tr>
</table>
<br>
<table border="0" width="100%" cellspacing="0" cellpadding="0">
  <tr>
    <td align="center" class="smallText">

Copyright © 2003 / 2004 - <a href="http://www.artsampa.com" target="_blank">Artsampa.com</a><br> Software Derivado de <a href="http://www.oscommerce.com" target="_blank">osCommerce</a>
   <P></td>
  </tr>
</table>
