<?php
/*
  $Id: mail.php,v 1.6 2001/11/19 11:39:24 hpdl Exp $

  The Exchange Project - Community Made Shopping!
  http://www.theexchangeproject.org

  Copyright (c) 2000,2001 The Exchange Project

  Released under the GNU General Public License
*/

define('TOP_BAR_TITLE', 'Mail');
define('HEADING_TITLE', 'Enviar Informativos a Cliente(s)');
define('SUB_BAR_TITLE', 'Escolha um cliente, clientes inscritos ou todos os clientes para enviar um e-mail.');

define('TEXT_CUSTOMER_NAME', 'Nome do Cliente:');
define('TEXT_SUBJECT', 'Assunto:');
define('TEXT_MESSAGE', 'Mensagem:');
define('TEXT_SELECTCUSTOMER', 'Selecionar Cliente');
define('TEXT_ALLCUSTOMERS', 'Todos os Clientes');
define('TEXT_NEWSLETTERCUSTOMERS', 'Todos os Inscritos');
define('TEXT_MSGTO', 'Mensagem para');
define('TEXT_EMAILSENT', 'Emails enviados');
define('TEXT_EMAILFROM', EMAIL_FROM);
define('TEXT_NO_EMAILS_TO_SEND', 'Não há e-mails para enviar.');
define('TEXT_EMAIL_FROM', 'From:');
define('TEXT_SEND_EMAIL', 'Para');
define('TEXT_NO_CUSTOMER_SELECTED', 'Não há cliente(s) selecionado(s) para enviar email!');

?>