<?php
/*
  $Id: modules.php,v 1.3 2001/09/19 11:12:58 mbs Exp $

  The Exchange Project - Community Made Shopping!
  http://www.theexchangeproject.org

  Copyright (c) 2000,2001 The Exchange Project

  Released under the GNU General Public License
*/

define('TOP_BAR_TITLE', 'Módulos');
define('HEADING_TITLE_MODULES_PAYMENT', 'Módulos de Pagamento');
define('HEADING_TITLE_MODULES_SHIPPING', 'Módulos de Envio');

define('TABLE_HEADING_CONFIGURATION_TITLE', 'Arquivo');
define('TABLE_HEADING_STATUS', 'Status');
define('TABLE_HEADING_ACTION', 'Ação');
?>
