<?php
/*
  $Id: orders.php,v 1.9 2001/12/09 18:29:01 dgw_ Exp $

  The Exchange Project - Community Made Shopping!
  http://www.theexchangeproject.org

  Copyright (c) 2000,2001 The Exchange Project

  Released under the GNU General Public License
*/

define('TOP_BAR_TITLE', 'Pedidos');
define('HEADING_TITLE', 'Pedidos');
define('HEADING_TITLE_SEARCH', 'insira a indentificação do pedido');

define('TABLE_HEADING_COMMENTS', 'Comentários');
define('TABLE_HEADING_CUSTOMERS', 'Clientes');
define('TABLE_HEADING_CUSTOMERS_INFO', 'Informação do Cliente');
define('TABLE_HEADING_DELIVERY_INFO', 'Informação de Entrega');
define('TABLE_HEADING_ORDER_TOTAL', 'Total Pedido');
define('TABLE_HEADING_PAYMENT_INFORMATION', 'Informação sobre o pagamento');
define('TABLE_HEADING_PAYMENT_METHOD', 'Método de Pagamento');
define('TABLE_HEADING_DATE_PURCHASED', 'Data da Compra');
define('TABLE_HEADING_STATUS', 'Status');
define('TABLE_HEADING_QUANTITY', 'Quantidade');
define('TABLE_HEADING_PRODUCTS_MODEL', 'Modelo');
define('TABLE_HEADING_PRODUCTS', 'Produtos');
define('TABLE_HEADING_TAX', 'Imposto');
define('TABLE_HEADING_TOTAL', 'Total');
define('TABLE_HEADING_STATUS', 'Status');

define('ENTRY_CUSTOMER', 'Cliente:');
define('ENTRY_STREET_ADDRESS', 'Endereço:');
define('ENTRY_SUBURB', 'Bairro:');
define('ENTRY_CITY', 'Cidade:');
define('ENTRY_POST_CODE', 'CEP:');
define('ENTRY_STATE', 'País:');
define('ENTRY_COUNTRY', 'Estado:');
define('ENTRY_TELEPHONE', 'Telefone:');
define('ENTRY_EMAIL_ADDRESS', 'E-Mail:');
define('ENTRY_DELIVERY_TO', 'Enviar a:');
define('ENTRY_PAYMENT_METHOD', 'Método de Pagamento:');
define('ENTRY_CREDIT_CARD_TYPE', 'Tipo de Cartão de Crédito:');
define('ENTRY_CREDIT_CARD_OWNER', 'Titular do Cartão de Crédito:');
define('ENTRY_CREDIT_CARD_NUMBER', 'Número do cartão de Crédito:');
define('ENTRY_CREDIT_CARD_EXPIRES', 'Vencimento do Cartão de Crédito:');
define('ENTRY_SUB_TOTAL', 'Subtotal:');
define('ENTRY_TAX', 'Impostos:');
define('ENTRY_SHIPPING', 'Gastos de Envio:');
define('ENTRY_TOTAL', 'Total:');
define('ENTRY_DATE_PURCHASED', 'Data da Compra:');
define('ENTRY_STATUS', 'Status:');
define('ENTRY_DATE_LAST_UPDATED', 'Última Modificação:');

define('TEXT_ORDER_INFORMATION', '<font color="#ff0000"><b>NOTA:</b></font> Clique sobre o nome do cliente para ver informações do pedido');
define('TEXT_UNKNOWN', 'Desconhecido');
?>
