<?php
/*
  $Id: reviews.php,v 1.3 2001/09/19 11:12:53 mbs Exp $

  The Exchange Project - Community Made Shopping!
  http://www.theexchangeproject.org

  Copyright (c) 2000,2001 The Exchange Project

  Released under the GNU General Public License
*/

define('TOP_BAR_TITLE', 'Comentários');
define('HEADING_TITLE', 'Comentários');

define('TABLE_HEADING_PRODUCTS', 'Produtos');
define('TABLE_HEADING_RATING', 'Avaliação');
define('TABLE_HEADING_DATE_ADDED', 'Data da entrada');
define('TABLE_HEADING_ACTION', 'Ação');

define('ENTRY_PRODUCT', 'Produto:');
define('ENTRY_FROM', 'De:');
define('ENTRY_DATE', 'Data:');
define('ENTRY_REVIEW', 'Comentário:');
define('ENTRY_REVIEW_TEXT', '<small><font color="#ff0000"><b>NOTA:</b></font></small>&nbsp;não se aceita HTML!&nbsp;');
define('ENTRY_RATING', 'Avaliação:');

define('TEXT_DELETE_REVIEW_INTRO', 'Tem certeza que deseja apagar este comentário?');

define('TEXT_DATE_ADDED', 'Data da Entrada:');
define('TEXT_LAST_MODIFIED', 'Última Modificação:');
define('TEXT_IMAGE_NONEXISTENT', 'NO EXISTE IMAGEN');
define('TEXT_REVIEW_AUTHOR', 'Autor:');
define('TEXT_REVIEW_RATING', 'Avaliação:');
define('TEXT_REVIEW_READ', 'Lido:');
define('TEXT_REVIEW_SIZE', 'Tamanho:');
define('TEXT_PRODUCTS_AVERAGE_RATING', 'Avaliação Média:');

define('TEXT_OF_5_STARS', '%s de 5 Estrelas!');
define('TEXT_GOOD', '<small><font color="#ff0000"><b>BOM</b></font></small>');
define('TEXT_BAD', '<small><font color="#ff0000"><b>MAL</b></font></small>');
?>