<?php
/*
  $Id: specials.php,v 1.7 2001/12/09 23:19:09 dgw_ Exp $

  The Exchange Project - Community Made Shopping!
  http://www.theexchangeproject.org

  Copyright (c) 2000,2001 The Exchange Project

  Released under the GNU General Public License
*/

define('TOP_BAR_TITLE', 'Ofertas');
define('HEADING_TITLE', 'Ofertas');

define('TABLE_HEADING_PRODUCTS', 'Produtos');
define('TABLE_HEADING_PRODUCTS_PRICE', 'Preço');
define('TABLE_HEADING_STATUS', 'Status');
define('TABLE_HEADING_ACTION', 'Ação');

define('TEXT_SPECIALS_PRODUCT', 'Produto:');
define('TEXT_SPECIALS_SPECIAL_PRICE', 'Preço de Oferta:');
define('TEXT_SPECIALS_EXPIRES_DATE', 'Data em que expira:');
define('TEXT_SPECIALS_PRICE_TIP', '<b>Notas:</b><ul><li>Pode inserir uma porcentagem de redução ao preço do produto, por exemplo: <b>20%</b></li><li>se inserir um novo preço, deve utilizar um ponto como separador decimal \'.\' (ponto decimal), por exemplo: <b>49.99</b></li><li>Deixe a data de expiração em branco se não deseja encerrar a oferta.</li></ul>');

define('TEXT_INFO_DATE_ADDED', 'Data de entrada:');
define('TEXT_INFO_LAST_MODIFIED', 'Última Modificação:');
define('TEXT_INFO_NEW_PRICE', 'Novo Preço:');
define('TEXT_INFO_ORIGINAL_PRICE', 'Preço Original:');
define('TEXT_INFO_PERCENTAGE', 'Porcentagem:');
define('TEXT_INFO_EXPIRES_AT', 'Data da Expiração: <b>%s</b>');
define('TEXT_INFO_STATUS_CHANGE', 'Trocar de Status: %s');

define('TEXT_INFO_DELETE_INTRO', 'Tem certeza que deseja eliminar esta oferta?');
?>
