<?php
/*
  $Id: zones.php,v 1.3 2001/09/19 11:12:45 mbs Exp $

  The Exchange Project - Community Made Shopping!
  http://www.theexchangeproject.org

  Copyright (c) 2000,2001 The Exchange Project

  Released under the GNU General Public License
*/

define('TOP_BAR_TITLE', 'Paises e seus Estados');
define('HEADING_TITLE', 'Paнses e seus Estados');

define('TABLE_HEADING_COUNTRY_NAME', 'Paнs');
define('TABLE_HEADING_ZONE_NAME', 'Estado');
define('TABLE_HEADING_ZONE_CODE', 'Cуdigo');
define('TABLE_HEADING_ACTION', 'Aзгo');

define('TEXT_INFO_EDIT_INTRO', 'Faзa as mudanзas necessбrias');
define('TEXT_INFO_ZONES_NAME', 'Nome do Estado:');
define('TEXT_INFO_ZONES_CODE', 'Cуdigo do Estado:');
define('TEXT_INFO_COUNTRY_NAME', 'Paнs:');
define('TEXT_INFO_INSERT_INTRO', 'Insira os dados do estado');
define('TEXT_INFO_DELETE_INTRO', 'Tem certeza que deseja eliminar este estado?');
define('TEXT_INFO_HEADING_NEW_ZONE', 'Novo Estado');
?>