<?php
/*
  $Id: index.php, v 2.2 24/07/2003 by Paulo Cezar - Artsampa Exp $

  osCommerce
  http://www.oscommerce.com/

  Artsampa - Graffiti Art Shop
  http://www.artsampa.com/

  Copyright (c) 2000,2003 osCommerce

  Released under the GNU General Public License
 
*/

  require('includes/application.php');

  $page_file = 'index.php';
  $page_title = 'Bem vindo a instalação da Loja Virtual 2.2';
  $page_contents = 'index.php';

  require('templates/main_page.php');
?>
